### ISSUE TITLE
unable to connect with tomcat in debug mode using eclipse using same method.

### ISSUE THREAD

**Issue by Yogendra0Sharma** [carlosCharz/jvisualvmtomcat#1]
EC2 tomcat -> /bin/setup.env 
```
export CATALINA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=9000,server=y,suspend=n"
export JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=9000,server=y,suspend=n"
```
setup tunnel and configure eclipse in debug mode.

**Comment by carlosCharz** [comment]
Hi, I have not tested with tomcat debug mode in Eclipse. I hope someone else can sort it out how to solve it. I will try to check it out. Thanks!

**Comment by Yogendra0Sharma** [comment]
> Hi, I have not tested with tomcat debug mode in Eclipse. I hope someone else can sort it out how to solve it. I will try to check it out. Thanks!

I resolve this issue. Thanks
We have to set following env variable in setenv.sh

`JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n $JPDA_OPTS"`

connect with eclipse:- 
debug configuration -> use localhost & 8000 port.
